# wrangler.toml

name = "moboy-earn"
compatibility_date = "2024-11-14"
compatibility_flags = ["nodejs_compat"]

# Kembalikan ke output directory adapter lama
pages_build_output_dir = ".vercel/output/static"