name = "moboy-post-to-earn"
main = "src/app/api/health/route.ts"
compatibility_date = "2024-01-15"

[env.production]
name = "moboy-post-to-earn-prod"

[[env.production.kv_namespaces]]
binding = "MOBOY_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[env.production.vars]
DATABASE_URL = "file:./dev.db"
NEXTAUTH_SECRET = "your-nextauth-secret"
NEXTAUTH_URL = "https://your-domain.pages.dev"

[env.development]
name = "moboy-post-to-earn-dev"

[[env.development.kv_namespaces]]
binding = "MOBOY_KV"
id = "your-dev-kv-namespace-id"

[env.development.vars]
DATABASE_URL = "file:./dev.db"
NEXTAUTH_SECRET = "your-nextauth-secret-dev"
NEXTAUTH_URL = "http://localhost:3000"