# wrangler.toml

name = "moboy-earn"
compatibility_date = "2024-11-14"
compatibility_flags = ["nodejs_compat"]

# Ini adalah bagian terpenting
pages_build_output_dir = ".vercel/output/static"

# [build] command akan otomatis diatur oleh adapter
# Jadi Anda tidak perlu menulisnya secara manual di sini